# Generated by Django 4.0.6 on 2022-09-01 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(blank=True, max_length=50, null=True)),
                ('quantity', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=6, null=True)),
                ('received_by', models.CharField(blank=True, max_length=50, null=True)),
                ('reorder_level', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_name', to='stock.category')),
            ],
            options={
                'verbose_name': 'Stock',
                'verbose_name_plural': 'Stocks',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='OrderTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('issued_by', models.CharField(blank=True, max_length=50, null=True)),
                ('fulfilled_by', models.CharField(blank=True, max_length=50, null=True)),
                ('remarks', models.TextField(max_length=255)),
                ('status', models.CharField(choices=[('PE', 'Pending'), ('AP', 'Approved'), ('PR', 'Processing'), ('RE', 'Rejected')], default='PE', max_length=2)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ord_cat_name', to='stock.category')),
                ('dep_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ord_dep_name', to='stock.department')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ord_item_name', to='stock.stock')),
            ],
            options={
                'verbose_name': 'OrderTicket',
                'verbose_name_plural': 'OrderTickets',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issued_by', models.CharField(blank=True, max_length=50, null=True)),
                ('issued_quantity', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_updated_by', models.CharField(blank=True, max_length=50, null=True)),
                ('issued_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issued_item_name', to='stock.stock')),
                ('issued_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_name', to='stock.department')),
                ('order_ticket_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ord_issue', to='stock.orderticket')),
            ],
            options={
                'verbose_name': 'Issue',
                'verbose_name_plural': 'Issues',
                'ordering': ('-issued_at',),
            },
        ),
        migrations.CreateModel(
            name='DepartmentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dep_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dep_name', to='stock.department')),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dep_item_name', to='stock.stock')),
            ],
            options={
                'verbose_name': 'DepartmentItem',
                'verbose_name_plural': 'DepartmentItems',
                'ordering': ('-last_updated_at',),
            },
        ),
    ]
